sudo: true
language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y povray
install:
  - python3 -m pip install --upgrade .[docs] coverage codecov
script:
  - python3 -m coverage run -m unittest -b
after_success:
  - python3 -m coverage xml -i
  - python3 -m codecov --file coverage.xml
